//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ps.dmv.infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class DmvCalculation
    {
        public DmvCalculation()
        {
            this.MobileDeCar = new HashSet<MobileDeCar>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateOfCalculation { get; set; }
        public int VehicleTypeId { get; set; }
        public int FuelTypeId { get; set; }
        public short Co2EmissionsValue { get; set; }
        public int EuroExhaustTypeId { get; set; }
        public bool AtLeastEightSeatsVehicle { get; set; }
        public int EnginePowerKw { get; set; }
        public int EngineDisplacementCcm { get; set; }
        public int EngineTypeId { get; set; }
        public int VehicleValue { get; set; }
        public int BaseTaxRate { get; set; }
        public double BaseTaxRateValue { get; set; }
        public int AdditionalTaxRate { get; set; }
        public double AdditionalTaxRateValue { get; set; }
        public double TaxTotalValue { get; set; }
        public bool IsDeleted { get; set; }
        public string UserId { get; set; }
        public bool DieselParticlesAbove005Limit { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual EngineType EngineType { get; set; }
        public virtual EuroExhaustType EuroExhaustType { get; set; }
        public virtual FuelType FuelType { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual ICollection<MobileDeCar> MobileDeCar { get; set; }
    }
}
