//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ps.dmv.infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class EuroExhaustType
    {
        public EuroExhaustType()
        {
            this.DmvCalculation = new HashSet<DmvCalculation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<DmvCalculation> DmvCalculation { get; set; }
    }
}
