//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ps.dmv.infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileDeCar
    {
        public MobileDeCar()
        {
            this.DmvCalculation1 = new HashSet<DmvCalculation>();
        }
    
        public int Id { get; set; }
        public string Url { get; set; }
        public int DmvCalculationId { get; set; }
        public string Maker { get; set; }
        public string Model { get; set; }
        public bool IsDeleted { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual DmvCalculation DmvCalculation { get; set; }
        public virtual ICollection<DmvCalculation> DmvCalculation1 { get; set; }
    }
}
