// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ps.dmv.web.Controllers
{
    public partial class DmvController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public DmvController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected DmvController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DmvCalculationResult()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DmvCalculationResult);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public DmvController Actions { get { return MVC.Dmv; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Dmv";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Dmv";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string DmvForm = "DmvForm";
            public readonly string DmvFormLite = "DmvFormLite";
            public readonly string DmvCalculationResult = "DmvCalculationResult";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string DmvForm = "DmvForm";
            public const string DmvFormLite = "DmvFormLite";
            public const string DmvCalculationResult = "DmvCalculationResult";
        }


        static readonly ActionParamsClass_DmvCalculationResult s_params_DmvCalculationResult = new ActionParamsClass_DmvCalculationResult();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DmvCalculationResult DmvCalculationResultParams { get { return s_params_DmvCalculationResult; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DmvCalculationResult
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _dmvCalculationForm = "_dmvCalculationForm";
                public readonly string _dmvCalculationFormLite = "_dmvCalculationFormLite";
                public readonly string DmvCalculationResult = "DmvCalculationResult";
                public readonly string Index = "Index";
            }
            public readonly string _dmvCalculationForm = "~/Views/Dmv/_dmvCalculationForm.cshtml";
            public readonly string _dmvCalculationFormLite = "~/Views/Dmv/_dmvCalculationFormLite.cshtml";
            public readonly string DmvCalculationResult = "~/Views/Dmv/DmvCalculationResult.cshtml";
            public readonly string Index = "~/Views/Dmv/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_DmvController : ps.dmv.web.Controllers.DmvController
    {
        public T4MVC_DmvController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void DmvFormOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult DmvForm()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DmvForm);
            DmvFormOverride(callInfo);
            return callInfo;
        }

        partial void DmvFormLiteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult DmvFormLite()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DmvFormLite);
            DmvFormLiteOverride(callInfo);
            return callInfo;
        }

        partial void DmvCalculationResultOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult DmvCalculationResult(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DmvCalculationResult);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DmvCalculationResultOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
